#spring.application.name=project-posgre
server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: danhson24520003@gmail.com
    password: voassocoddqczgbe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  expiration: 2592000
  expiration-refresh-token: 5184000
  secretKey: j+RfyDZuGgHqEpXBkDyQ7uW64sVKbzOyoGsmkSIN/7k=
  refreshKey: dYOd6awV6VhxKqZFYke5qCE43jy8IT0BAhMPT+Cqrp4=
  resetKey: GiN0mfEESNvE/b4qFiFoUHC5taclo848pAjDyPlDBAk=
api:
  prefix: api
vnpay:
  tmncode: 6XQZK7KQ
  hashsecret: QK78SNTOVW0I6S1ML7BDSJW9WSAH0T5M
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnurl: http://localhost:3000/dashboard/payment/vnpay-return
  ipnurl: http://localhost:8081/api/payment/vnpay-ipn

